[package]
name = "BGX13P_lib_rust"
version = "0.1.0"
authors = ["Christian Albrecht <christianalbrechtca@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4.17"
nom = "7.1.1"
serialport = "4.2.0"
tap = "1.0.1"
thiserror = "1.0.32"

[dev-dependencies]
simple_logger = "2.3.0"
