[package]
name = "BGX13P_lib_rust"
version = "0.1.0"
authors = ["Christian Albrecht <christianalbrechtca@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0"
log = "0.4"
anyhow = "1.0.41"
thiserror = "1.0.25"
combine = "4.6.0"

[dev-dependencies]
simple_logger = "1.13.0"
