[package]
name = "BGX13P_lib_rust"
version = "0.1.0"
authors = ["Christian Albrecht <christianalbrechtca@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.80"
log = "0.4.21"
tap = "1.0.1"
thiserror = "1.0.57"
winnow = "=0.3.8"

[dev-dependencies]
simple_logger = "4.3.3"
